language: python
python:
  - 3.8
install:
  - pip install -q -r requirements-dev.txt codecov
script:
  - flake8
  - pytest libpytthonpro --cov=libpytthonpro

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)